# EmbedManifest.cmake — Convert a manifest.json into a C++ header with a constexpr string.
#
# Usage:
#   include(${CMAKE_CURRENT_LIST_DIR}/../cmake/EmbedManifest.cmake)
#   pj_embed_manifest(my_target
#     HEADER   ${CMAKE_CURRENT_BINARY_DIR}/generated/manifest.hpp
#     VAR_NAME kMyManifest
#   )
#
# Optional:
#   MANIFEST_FILE  path/to/manifest.json   (default: ${CMAKE_CURRENT_SOURCE_DIR}/manifest.json)
#
# This reads the JSON file at configure time and generates a header like:
#   inline constexpr char kMyManifest[] = { 0x7b, ... , 0x00 };
#
# The manifest file is tracked as a configure dependency — editing it triggers
# CMake reconfiguration and header regeneration.

function(pj_embed_manifest TARGET)
  cmake_parse_arguments(ARG "" "MANIFEST_FILE;HEADER;VAR_NAME" "" ${ARGN})

  if(NOT ARG_HEADER OR NOT ARG_VAR_NAME)
    message(FATAL_ERROR "pj_embed_manifest: HEADER and VAR_NAME are required")
  endif()

  if(NOT ARG_MANIFEST_FILE)
    set(ARG_MANIFEST_FILE "${CMAKE_CURRENT_SOURCE_DIR}/manifest.json")
  endif()

  # Track the manifest file so CMake reconfigures when it changes
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ARG_MANIFEST_FILE}")

  # Get just the filename for the comment
  get_filename_component(_manifest_filename "${ARG_MANIFEST_FILE}" NAME)

  # Use hex-encoded char array to avoid MSVC's 16380-char string literal limit (C2026).
  file(READ "${ARG_MANIFEST_FILE}" _manifest_hex HEX)
  # Insert "0x" prefix and ", 0x" between each pair of hex digits
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _byte_list "${_manifest_hex}")

  # Generate the header with a char array initializer + null terminator
  file(WRITE "${ARG_HEADER}"
    "#pragma once\n"
    "// Auto-generated from ${_manifest_filename} — edit the .json file, not this header.\n"
    "// Regenerated by CMake at configure time.\n"
    "inline constexpr char ${ARG_VAR_NAME}[] = {\n"
    "${_byte_list}0x00};\n"
  )

  # Add the generated directory to include path
  get_filename_component(_gen_dir "${ARG_HEADER}" DIRECTORY)
  target_include_directories(${TARGET} PRIVATE "${_gen_dir}")
endfunction()
