# EmbedUi.cmake — Convert a .ui file into a C++ header with the XML as a constexpr string.
#
# Usage:
#   include(${CMAKE_CURRENT_LIST_DIR}/../cmake/EmbedUi.cmake)
#   pj_embed_ui(my_target
#     UI_FILE  ${CMAKE_CURRENT_SOURCE_DIR}/ui/dialog.ui
#     HEADER   ${CMAKE_CURRENT_BINARY_DIR}/generated/dialog_ui.hpp
#     VAR_NAME kDialogUi
#   )
#
# This reads the .ui file at configure time and generates a header like:
#   inline constexpr char kDialogUi[] = R"PJ_UI(... xml ...)PJ_UI";
#
# The .ui file is tracked as a configure dependency — editing it triggers
# CMake reconfiguration and header regeneration.

function(pj_embed_ui TARGET)
  cmake_parse_arguments(ARG "" "UI_FILE;HEADER;VAR_NAME" "" ${ARGN})

  if(NOT ARG_UI_FILE OR NOT ARG_HEADER OR NOT ARG_VAR_NAME)
    message(FATAL_ERROR "pj_embed_ui: UI_FILE, HEADER, and VAR_NAME are required")
  endif()

  # Track the .ui file so CMake reconfigures when it changes
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ARG_UI_FILE}")

  # Read the .ui XML content
  file(READ "${ARG_UI_FILE}" _ui_content)

  # Get just the filename for the comment
  get_filename_component(_ui_filename "${ARG_UI_FILE}" NAME)

  # Generate the header
  file(WRITE "${ARG_HEADER}"
    "#pragma once\n"
    "// Auto-generated from ${_ui_filename} — edit the .ui file, not this header.\n"
    "// Regenerated by CMake at configure time.\n"
    "inline constexpr char ${ARG_VAR_NAME}[] = R\"PJ_UI("
    "${_ui_content}"
    ")PJ_UI\";\n"
  )

  # Add the generated directory to include path
  get_filename_component(_gen_dir "${ARG_HEADER}" DIRECTORY)
  target_include_directories(${TARGET} PRIVATE "${_gen_dir}")
endfunction()
