name: CI Windows

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ci-windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Conan
        run: pip install conan

      - name: Install cmake and ninja
        run: pip install cmake ninja

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure plotjuggler cloudsmith Conan remote
        env:
          CLOUDSMITH_USER: ${{ secrets.CLOUDSMITH_USER }}
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        shell: bash
        run: |
          conan profile detect --force
          conan remote add plotjuggler-cloudsmith \
            https://conan.cloudsmith.io/plotjuggler/plotjuggler --force
          conan remote login plotjuggler-cloudsmith \
            "$CLOUDSMITH_USER" -p "$CLOUDSMITH_API_KEY"

      - name: Build & Test
        shell: bash
        run: |
          conan install . --output-folder=build --build=missing -s build_type=Release \
            -s compiler.cppstd=20 -c tools.cmake.cmaketoolchain:generator=Ninja \
            -o "cpython/*:shared=True"

          cmake -S . -B build/Release -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake \
            -DCMAKE_PREFIX_PATH=build \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build/Release --config Release
          ctest --test-dir build/Release -V --output-on-failure
